services:
  app:
    build: ./app
    container_name: workana_bot
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./browser_data:/usr/src/app/browser_data
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    # Mantiene el contenedor activo para desarrollo
    tty: true
    networks:
      - workana_network

  api:
    build: ./app
    container_name: workana_api
    restart: always
    working_dir: /usr/src
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - workana_network

  mongodb:
    image: mongo:8.0.4
    container_name: workana_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - workana_network

networks:
  workana_network:
    driver: bridge
