[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
# Requires pytest-dotenv plugin to be installed
env_files = .env.test
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
